version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt
      - pip install pytest
  pre_build:
    commands:
      - echo Start pre-build...
  build:
    commands:
      - echo Running unit tests with pytest...
      - pytest --junitxml=reports/results.xml --tb=short
  post_build:
    commands:
      - echo Build completed successfully.

artifacts:
  files:
    - "**/*"
  base-directory: .

reports:
  pytest-reports:
    files:
      - "reports/results.xml"
    discard-paths: yes
